services:
  backend:
    build: ./backend
    image: ${DOCKER_USERNAME}/gacha-backend:latest
    container_name: gacha-backend
    restart: always
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=restaurant_gacha
      - DB_PORT=3306 # Force internal port
    depends_on:
      - mysql_db
    networks:
      - web-network

  frontend:
    build: ./frontend
    image: ${DOCKER_USERNAME}/gacha-frontend:latest
    container_name: gacha-frontend
    restart: always
    # ports:
    #   - "8080:80" # 透過 Nginx 轉發，不需要直接暴露 Port
    depends_on:
      - backend
    networks:
      - web-network

  mysql_db:
    build: ./database
    image: ${DOCKER_USERNAME}/gacha-mysql:latest # Use our custom image with schema baked in!
    container_name: gacha-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: restaurant_gacha
    ports:
      - "3308:3306" # Sync with local testing success
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web-network

networks:
  web-network:
    external: true

volumes:
  db_data:
